### PR TITLE
Add Catalan && temperature converter && battle simulator

### PR DESCRIPTION
**Pull request by Tulip-0333**
I contribute to this too often

### CODE REVIEW

**Comment by virejdasani** [comment]
i appreciate youwu a lot but i don't think we need a conwibuwutews. txt becase all contributors are mentioned in the repo contributors section. can you delete that file please
thanks again!

**Comment by Tulip-0333** [comment]
Ok Virej!

**Comment by Tulip-0333** [comment]
Alright done

**Comment by Tulip-0333** [comment]
Um excuse me uwu are you gonna merge it

**Comment by virejdasani** [comment]
Thank youwu so much for contributing <3

**Pull request merged**
